export const educationData = [
  {
    school: "uam.school",
    degree: "uam.degree",
    years: "uam.years",
    description: "uam.description",
    tools: [
      "uam.tools.AlgorithmsAndDataStructures",
      "uam.tools.Python",
      "uam.tools.R",
      "uam.tools.SQL",
      "uam.tools.PowerBI",
      "uam.tools.OLAP",
      "uam.tools.MDX",
      "uam.tools.Statistics",
      "uam.tools.RecommenderSystems",
    ],
  },
  {
    school: "pp.school",
    degree: "pp.degree",
    years: "pp.years",
    description: "pp.description",
    tools: [
      "pp.tools.Python",
      "pp.tools.R",
      "pp.tools.DataExploration",
      "pp.tools.DataWarehouses",
      "pp.tools.ETL",
      "pp.tools.DataVisualization",
    ],
  },
  {
    school: "uep.school",
    degree: "uep.degree",
    years: "uep.years",
    description: "uep.description",
    tools: [
      "uep.tools.Python",
      "uep.tools.R",
      "uep.tools.SQL",
      "uep.tools.PowerBI",
      "uep.tools.DAX",
      "uep.tools.Statistics",
      "uep.tools.DataVisualization",
      "uep.tools.RegressionAnalysis",
      "uep.tools.CaseStudies",
    ],
  },
];